DROP TABLE If exists  CDMPv532.dose_era;

CREATE TABLE CDMPv532.DOSE_ERA
( dose_era_id				BIGINT	GENERATED BY DEFAULT AS IDENTITY		NOT NULL ,
  person_id					BIGINT			NOT NULL ,
  drug_concept_id			INTEGER			NOT NULL ,
  unit_concept_id			INTEGER			NOT NULL ,
  dose_value				NUMERIC		 	NOT NULL ,
  dose_era_start_date    	DATE		    NOT NULL ,
  dose_era_end_date 		DATE		    NOT NULL
);
